source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target 'lynx' do
project 'lynx.xcodeproj'
workspace 'lynx.xcworkspace'
pod 'SDWebImage', '~> 4.0'
pod 'SDWebImage/WebP'
pod 'AFNetworking', '~> 3.0'
end

target 'unittests' do
project 'unittests.xcodeproj'
workspace 'lynx.xcworkspace'
pod 'SDWebImage', '~> 4.0'
pod 'SDWebImage/WebP'
pod 'AFNetworking', '~> 3.0'
end